# This file was generated by GoReleaser. DO NOT EDIT.
cask "comrade" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "655581c816ce8b94a379960edb2938c80cd9553dc5b0209bb95a07863d2f3a87"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2de1cd4eb5dd03560ae523460f816d02886d8ac50b4ef8e432161d0c8489506"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cbc1f52ed3d38bfe20adfb32f1ac84e17a1d96575e8d390b5bdedaabc18a0400"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad6f33deed483515f962a4ebd305ca5ff9eb714db262d9f2097c3202a192ce5a"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_linux_arm64.tar.gz"
    end
  end

  name "comrade"
  desc "Cross-platform AI CLI companion for the terminal (TR/EN)."
  homepage "https://github.com/firatkutay/cli-comrade"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comrade"

  # No zap stanza required

end
