# This file was generated by GoReleaser. DO NOT EDIT.
cask "comrade" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "3e29f4afc29fa7951ba87dc4ca225f0270d8d5e4defc3e8f17f617fd87e1a304"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "950f29565cb187ad7bfc23945bf8f0c5e4cda94269d4230b08d1fb5bd3d63a50"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "416812d5cb50e4d9a42f1b01e809efdfc960e8ef2d3e1975d0a3f09249dd1e9c"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c190f33b946a92bd84afb033b86f59a13840448574151272400f482b649107f"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_linux_arm64.tar.gz"
    end
  end

  name "comrade"
  desc "Cross-platform AI CLI companion for the terminal (TR/EN)."
  homepage "https://github.com/firatkutay/cli-comrade"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comrade"

  # No zap stanza required

end
