# This file was generated by GoReleaser. DO NOT EDIT.
cask "comrade" do
  version "0.4.6"

  on_macos do
    on_intel do
      sha256 "cfe57886bf9433948c841d5722018f3a8d2ae6f527f68f160eadd0198c164f6f"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa0f0774ff02eef6697e91abbdb5b251a4d2e9082426cbc35522c197392991bb"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1f341e26732bc020eb31574ae7188e1f43e418f5acdf2c0e50605db1387cbb9"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e2d6aee48847dfe85b64e8931af2eecd82ff29c87a21f767f4833307f642c6d"
      url "https://github.com/firatkutay/cli-comrade/releases/download/v#{version}/comrade_#{version}_linux_arm64.tar.gz"
    end
  end

  name "comrade"
  desc "Cross-platform AI CLI companion for the terminal (TR/EN)."
  homepage "https://github.com/firatkutay/cli-comrade"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "comrade"

  # No zap stanza required

end
